// Generated by gencpp from file navigation/CurrentPos.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_CURRENTPOS_H
#define NAVIGATION_MESSAGE_CURRENTPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct CurrentPos_
{
  typedef CurrentPos_<ContainerAllocator> Type;

  CurrentPos_()
    : posX(0.0)
    , posY(0.0)
    , alpha(0.0)  {
    }
  CurrentPos_(const ContainerAllocator& _alloc)
    : posX(0.0)
    , posY(0.0)
    , alpha(0.0)  {
  (void)_alloc;
    }



   typedef float _posX_type;
  _posX_type posX;

   typedef float _posY_type;
  _posY_type posY;

   typedef float _alpha_type;
  _alpha_type alpha;





  typedef boost::shared_ptr< ::navigation::CurrentPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::CurrentPos_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentPos_

typedef ::navigation::CurrentPos_<std::allocator<void> > CurrentPos;

typedef boost::shared_ptr< ::navigation::CurrentPos > CurrentPosPtr;
typedef boost::shared_ptr< ::navigation::CurrentPos const> CurrentPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::CurrentPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::CurrentPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'navigation': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_navigation/navigation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CurrentPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CurrentPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::CurrentPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::CurrentPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CurrentPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CurrentPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::CurrentPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "541b695709a53604a4ebf6a833186a0b";
  }

  static const char* value(const ::navigation::CurrentPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x541b695709a53604ULL;
  static const uint64_t static_value2 = 0xa4ebf6a833186a0bULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::CurrentPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/CurrentPos";
  }

  static const char* value(const ::navigation::CurrentPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::CurrentPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 posX\n\
float32 posY\n\
float32 alpha\n\
";
  }

  static const char* value(const ::navigation::CurrentPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::CurrentPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.alpha);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::CurrentPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::CurrentPos_<ContainerAllocator>& v)
  {
    s << indent << "posX: ";
    Printer<float>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<float>::stream(s, indent + "  ", v.posY);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_CURRENTPOS_H
