// Generated by gencpp from file mbot_nlu/ActionSlotArray.msg
// DO NOT EDIT!


#ifndef MBOT_NLU_MESSAGE_ACTIONSLOTARRAY_H
#define MBOT_NLU_MESSAGE_ACTIONSLOTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mbot_nlu/ActionSlot.h>

namespace mbot_nlu
{
template <class ContainerAllocator>
struct ActionSlotArray_
{
  typedef ActionSlotArray_<ContainerAllocator> Type;

  ActionSlotArray_()
    : sentence_recognition()  {
    }
  ActionSlotArray_(const ContainerAllocator& _alloc)
    : sentence_recognition(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mbot_nlu::ActionSlot_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mbot_nlu::ActionSlot_<ContainerAllocator> >::other >  _sentence_recognition_type;
  _sentence_recognition_type sentence_recognition;





  typedef boost::shared_ptr< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> const> ConstPtr;

}; // struct ActionSlotArray_

typedef ::mbot_nlu::ActionSlotArray_<std::allocator<void> > ActionSlotArray;

typedef boost::shared_ptr< ::mbot_nlu::ActionSlotArray > ActionSlotArrayPtr;
typedef boost::shared_ptr< ::mbot_nlu::ActionSlotArray const> ActionSlotArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mbot_nlu::ActionSlotArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mbot_nlu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mbot_nlu': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_dialog/mbot_natural_language_processing/mbot_nlu/ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ac2cee11a45480fcd32ce9716a74e6d";
  }

  static const char* value(const ::mbot_nlu::ActionSlotArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ac2cee11a45480fULL;
  static const uint64_t static_value2 = 0xcd32ce9716a74e6dULL;
};

template<class ContainerAllocator>
struct DataType< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mbot_nlu/ActionSlotArray";
  }

  static const char* value(const ::mbot_nlu::ActionSlotArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# a sentence gets divided into phrases and for each\n\
# phrase you get an intention and arguments, therefore\n\
# in the case of having one phrase to recognize the lenght\n\
# of this array should be 1\n\
ActionSlot[] sentence_recognition\n\
\n\
================================================================================\n\
MSG: mbot_nlu/ActionSlot\n\
string intention\n\
Slot[] slots\n\
\n\
================================================================================\n\
MSG: mbot_nlu/Slot\n\
string type\n\
string data\n\
";
  }

  static const char* value(const ::mbot_nlu::ActionSlotArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentence_recognition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionSlotArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mbot_nlu::ActionSlotArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mbot_nlu::ActionSlotArray_<ContainerAllocator>& v)
  {
    s << indent << "sentence_recognition[]" << std::endl;
    for (size_t i = 0; i < v.sentence_recognition.size(); ++i)
    {
      s << indent << "  sentence_recognition[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mbot_nlu::ActionSlot_<ContainerAllocator> >::stream(s, indent + "    ", v.sentence_recognition[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MBOT_NLU_MESSAGE_ACTIONSLOTARRAY_H
