// Generated by gencpp from file mbot_nlu/Slot.msg
// DO NOT EDIT!


#ifndef MBOT_NLU_MESSAGE_SLOT_H
#define MBOT_NLU_MESSAGE_SLOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mbot_nlu
{
template <class ContainerAllocator>
struct Slot_
{
  typedef Slot_<ContainerAllocator> Type;

  Slot_()
    : type()
    , data()  {
    }
  Slot_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mbot_nlu::Slot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mbot_nlu::Slot_<ContainerAllocator> const> ConstPtr;

}; // struct Slot_

typedef ::mbot_nlu::Slot_<std::allocator<void> > Slot;

typedef boost::shared_ptr< ::mbot_nlu::Slot > SlotPtr;
typedef boost::shared_ptr< ::mbot_nlu::Slot const> SlotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mbot_nlu::Slot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mbot_nlu::Slot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mbot_nlu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mbot_nlu': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_dialog/mbot_natural_language_processing/mbot_nlu/ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mbot_nlu::Slot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mbot_nlu::Slot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mbot_nlu::Slot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mbot_nlu::Slot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_nlu::Slot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_nlu::Slot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mbot_nlu::Slot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "167124529e10dda68e69162baeaee3b8";
  }

  static const char* value(const ::mbot_nlu::Slot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x167124529e10dda6ULL;
  static const uint64_t static_value2 = 0x8e69162baeaee3b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mbot_nlu::Slot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mbot_nlu/Slot";
  }

  static const char* value(const ::mbot_nlu::Slot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mbot_nlu::Slot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n\
string data\n\
";
  }

  static const char* value(const ::mbot_nlu::Slot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mbot_nlu::Slot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Slot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mbot_nlu::Slot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mbot_nlu::Slot_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MBOT_NLU_MESSAGE_SLOT_H
