// Generated by gencpp from file dialog/listenRequest.msg
// DO NOT EDIT!


#ifndef DIALOG_MESSAGE_LISTENREQUEST_H
#define DIALOG_MESSAGE_LISTENREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dialog
{
template <class ContainerAllocator>
struct listenRequest_
{
  typedef listenRequest_<ContainerAllocator> Type;

  listenRequest_()
    : send()  {
    }
  listenRequest_(const ContainerAllocator& _alloc)
    : send(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _send_type;
  _send_type send;





  typedef boost::shared_ptr< ::dialog::listenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialog::listenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct listenRequest_

typedef ::dialog::listenRequest_<std::allocator<void> > listenRequest;

typedef boost::shared_ptr< ::dialog::listenRequest > listenRequestPtr;
typedef boost::shared_ptr< ::dialog::listenRequest const> listenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialog::listenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialog::listenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dialog

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dialog': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_dialog/dialog/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dialog::listenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialog::listenRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::listenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::listenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::listenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::listenRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialog::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b903a44705b40a7116d3d10341f60dfc";
  }

  static const char* value(const ::dialog::listenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb903a44705b40a71ULL;
  static const uint64_t static_value2 = 0x16d3d10341f60dfcULL;
};

template<class ContainerAllocator>
struct DataType< ::dialog::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialog/listenRequest";
  }

  static const char* value(const ::dialog::listenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialog::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string send\n\
";
  }

  static const char* value(const ::dialog::listenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialog::listenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.send);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct listenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialog::listenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialog::listenRequest_<ContainerAllocator>& v)
  {
    s << indent << "send: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.send);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOG_MESSAGE_LISTENREQUEST_H
