// Generated by gencpp from file dialog/speakRequest.msg
// DO NOT EDIT!


#ifndef DIALOG_MESSAGE_SPEAKREQUEST_H
#define DIALOG_MESSAGE_SPEAKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dialog
{
template <class ContainerAllocator>
struct speakRequest_
{
  typedef speakRequest_<ContainerAllocator> Type;

  speakRequest_()
    : text_t2s()  {
    }
  speakRequest_(const ContainerAllocator& _alloc)
    : text_t2s(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_t2s_type;
  _text_t2s_type text_t2s;





  typedef boost::shared_ptr< ::dialog::speakRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialog::speakRequest_<ContainerAllocator> const> ConstPtr;

}; // struct speakRequest_

typedef ::dialog::speakRequest_<std::allocator<void> > speakRequest;

typedef boost::shared_ptr< ::dialog::speakRequest > speakRequestPtr;
typedef boost::shared_ptr< ::dialog::speakRequest const> speakRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialog::speakRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialog::speakRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dialog

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dialog': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_dialog/dialog/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dialog::speakRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialog::speakRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::speakRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::speakRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::speakRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::speakRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialog::speakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "072ffd09f62c868e11497d5fe88416e3";
  }

  static const char* value(const ::dialog::speakRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x072ffd09f62c868eULL;
  static const uint64_t static_value2 = 0x11497d5fe88416e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::dialog::speakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialog/speakRequest";
  }

  static const char* value(const ::dialog::speakRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialog::speakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text_t2s\n\
";
  }

  static const char* value(const ::dialog::speakRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialog::speakRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text_t2s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speakRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialog::speakRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialog::speakRequest_<ContainerAllocator>& v)
  {
    s << indent << "text_t2s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text_t2s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOG_MESSAGE_SPEAKREQUEST_H
