// Generated by gencpp from file dialog/Wav.msg
// DO NOT EDIT!


#ifndef DIALOG_MESSAGE_WAV_H
#define DIALOG_MESSAGE_WAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dialog
{
template <class ContainerAllocator>
struct Wav_
{
  typedef Wav_<ContainerAllocator> Type;

  Wav_()
    : fs(0)
    , chl()
    , chr()  {
    }
  Wav_(const ContainerAllocator& _alloc)
    : fs(0)
    , chl(_alloc)
    , chr(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _fs_type;
  _fs_type fs;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _chl_type;
  _chl_type chl;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _chr_type;
  _chr_type chr;





  typedef boost::shared_ptr< ::dialog::Wav_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialog::Wav_<ContainerAllocator> const> ConstPtr;

}; // struct Wav_

typedef ::dialog::Wav_<std::allocator<void> > Wav;

typedef boost::shared_ptr< ::dialog::Wav > WavPtr;
typedef boost::shared_ptr< ::dialog::Wav const> WavConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialog::Wav_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialog::Wav_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dialog

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dialog': ['/home/maelic/robobreizh_simu_ws/src/robobreizh_dialog/dialog/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dialog::Wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialog::Wav_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::Wav_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialog::Wav_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::Wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialog::Wav_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialog::Wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd12d0f67404dd8368da8a8a7e79c981";
  }

  static const char* value(const ::dialog::Wav_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd12d0f67404dd83ULL;
  static const uint64_t static_value2 = 0x68da8a8a7e79c981ULL;
};

template<class ContainerAllocator>
struct DataType< ::dialog::Wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialog/Wav";
  }

  static const char* value(const ::dialog::Wav_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialog::Wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 fs\n\
float32[] chl\n\
float32[] chr\n\
";
  }

  static const char* value(const ::dialog::Wav_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialog::Wav_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fs);
      stream.next(m.chl);
      stream.next(m.chr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wav_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialog::Wav_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialog::Wav_<ContainerAllocator>& v)
  {
    s << indent << "fs: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fs);
    s << indent << "chl[]" << std::endl;
    for (size_t i = 0; i < v.chl.size(); ++i)
    {
      s << indent << "  chl[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.chl[i]);
    }
    s << indent << "chr[]" << std::endl;
    for (size_t i = 0; i < v.chr.size(); ++i)
    {
      s << indent << "  chr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.chr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOG_MESSAGE_WAV_H
